- collections:
  - dellemc.os10
  connection: network_cli
  gather_facts: false
  hosts: fabric 
  pre_tasks:
  - name: PreConfigs
    os10_config:
      src: '{{ hostname }}.j2.pre'
    when: preconf_path is exists
  roles:
  - os10_vrf
  - os10_interface
  - os10_vlan
  - os10_lag
  - os10_vlt
  - os10_lldp
  - os10_system
  - os10_users
  - os10_route_map
  - os10_ecmp
  - os10_prefix_list
  - os10_bgp
  - os10_xstp
  - os10_snmp
  - os10_ntp
  - os10_logging
  - os10_copy_config
  - os10_vrrp
  vars:
  - preconf_path: templates/{{ hostname }}.j2.pre
