hostname: fabric-LEAF-4
os10_bgp:
  asn: 64626
  best_path:
    as_path: multipath-relax
  graceful_restart: true
  maxpath_ebgp: 2
  neighbor:
  - adv_interval: 1
    fall_over: present
    name: spine-leaf
    timer: 3 9
    type: peergroup
  - address_family:
    - allow_as_in: 1
      type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.6
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    timer: 3 9
    type: ipv4
  - address_family:
    - allow_as_in: 1
      type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.2.6
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    timer: 3 9
    type: ipv4
  - admin: up
    ip: 192.168.3.2
    remote_asn: 64626
    type: ipv4
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.1
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    timer: 3 9
    type: ipv4
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.2
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    timer: 3 9
    type: ipv4
  redistribute:
  - address_type: ipv4
    route_map_name: spine-leaf
    route_type: connected
  router_id: 10.0.2.4
os10_interface:
  ethernet 1/1/1:
    admin: up
    desc: Node-2_eth1-NDC1-1G-2
    mtu: 9216
    switchport: false
  ethernet 1/1/8:
    admin: up
    desc: VLT to fabric-LEAF-3 1/1/8
    switchport: false
  ethernet 1/1/9:
    admin: up
    desc: VLT to fabric-LEAF-3 1/1/9
    switchport: false
  ethernet 1/1/4:
    admin: up
    desc: Uplink
    mtu: 9216
    portmode: trunk
    switchport: true
  ethernet 1/1/5:
    admin: up
    desc: Uplink
    mtu: 9216
    portmode: trunk
    switchport: true
  ethernet 1/1/7:
    admin: up
    desc: Uplink to fabric-SPINE-2 1/1/4
    ip_and_mask: 192.168.2.7/31
    mtu: 9216
    switchport: false
  ethernet 1/1/6:
    admin: up
    desc: Uplink to fabric-SPINE-1 1/1/4
    ip_and_mask: 192.168.1.7/31
    mtu: 9216
    switchport: false
  loopback 0:
    admin: up
    ip_and_mask: 10.0.2.4/32
  loopback 1:
    admin: up
    ip_and_mask: 1.0.1.2/32
os10_lag:
  Po 10:
    admin: up
    state: present
    type: dynamic
os10_lldp:
  enable: true
os10_ntp:
  server:
  - ip: 10.204.9.254
    prefer: true
os10_prefix_list:
- entries:
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 10.0.0.0
    number: 10
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 1.0.0.0
    number: 20
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 192.168.0.0
    number: 30
    permit: true
    state: present
  name: spine-leaf
  state: present
  type: ipv4
os10_route_map:
  route_map:
  - match:
    - ip_type: ipv4
      prefix_list: spine-leaf
    name: spine-leaf
    permit: true
    seq_num: 10
os10_system:
  hostname: fabric-LEAF-4
os10_vlan:
  Vlan 201:
    description: Compute_2_Management
    ip_and_mask: null
    state: present
    tagged_members:
    - port: Po 10
      state: present
  Vlan 4000:
    description: iBGP_link
    ip_and_mask: 192.168.3.3/31
    state: present
os10_vlt:
  discovery_intf: 1/1/8-1/1/9
  discovery_intf_state: present
  domain: 127
  peer_routing: true
  vlt_mac: 00:00:00:00:00:34
  vlt_peers:
    Po 10:
      peer_lag: 10
os10_xstp:
  enable: true
  intf:
    Po 10:
      bpdu_guard: true
      edge_port: true
      guard: root
  rstp:
    bridge_priority: 4096
  type: rstp
