hostname: fabric-LEAF-2
os10_bgp:
  asn: 64625
  best_path:
    as_path: multipath-relax
  graceful_restart: true
  maxpath_ebgp: 2
  neighbor:
  - adv_interval: 1
    fall_over: present
    name: spine-leaf
    timer: 3 9
    type: peergroup
  - adv_interval: 1
    fall_over: present
    name: spine-leaf-evpn
    timer: 3 9
    type: peergroup
    src_loopback: 0
  - address_family:
    - allow_as_in: 1
      type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.1.2
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    timer: 3 9
    type: ipv4
  - address_family:
    - allow_as_in: 1
      type: ipv4
    admin: up
    adv_interval: 1
    fall_over: present
    ip: 192.168.2.2
    name: spine-leaf
    peergroup: spine-leaf
    remote_asn: 64600
    timer: 3 9
    type: ipv4
  - admin: up
    ip: 192.168.3.0
    remote_asn: 64625
    type: ipv4
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.1
    name: spine-leaf
    peergroup: spine-leaf-evpn
    remote_asn: 64600
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    timer: 3 9
    type: ipv4
  - address_family:
    - activate: false
      type: ipv4
    - activate: true
      type: l2vpn
    admin: up
    adv_interval: 1
    ebgp_multihop: 4
    fall_over: present
    ip: 10.0.1.2
    name: spine-leaf
    peergroup: spine-leaf-evpn
    remote_asn: 64600
    send_community:
    - state: present
      type: extended
    sender_loop_detect: false
    timer: 3 9
    type: ipv4
  redistribute:
  - address_type: ipv4
    route_map_name: spine-leaf
    route_type: connected
  router_id: 10.0.2.2
  vrf:
    address_family:
      redistribute:
      - route_type: l2vpn evpn
      - route_type: l2vpn evpn route-map deny_v4_host_routes
      - route_type: connected
      type: ipv4
    name: tenant1
    neighbor:
    - address_family:
      - allow_as_in: 1
        type: ipv4
      admin: up
      ip: 1.1.1.5
      remote_asn: 64444
      type: ipv4
    - address_family:
      - allow_as_in: 1
        type: ipv4
      admin: up
      ip: 1.1.1.7
      remote_asn: 64444
      type: ipv4
os10_interface:
  ethernet 1/1/4:
    admin: up
    desc: Uplink
    mtu: 9216
    portmode: trunk
    switchport: true
  ethernet 1/1/5:
    admin: up
    desc: Uplink
    mtu: 9216
    portmode: trunk
    switchport: true
  ethernet 1/1/1:
    switchport: true
    desc: Node-1_eth0-NDC1-1G-2
    mtu: 9216
    admin: up
  ethernet 1/1/8:
    admin: up
    desc: VLT to fabric-LEAF-1 1/1/8
    switchport: false
  ethernet 1/1/9:
    admin: up
    desc: VLT to fabric-LEAF-1 1/1/9
    switchport: false
  ethernet 1/1/7:
    admin: up
    desc: Uplink to fabric-SPINE-2 1/1/2
    ip_and_mask: 192.168.2.3/31
    mtu: 9216
    switchport: false
  ethernet 1/1/6:
    admin: up
    desc: Uplink to fabric-SPINE-1 1/1/2
    ip_and_mask: 192.168.1.3/31
    mtu: 9216
    switchport: false
  loopback 0:
    admin: up
    ip_and_mask: 10.0.2.2/32
  loopback 1:
    admin: up
    ip_and_mask: 1.0.1.1/32
  vlan 12:
    vrf: tenant1
os10_lldp:
  enable: true
os10_ntp:
  server:
  - ip: 10.204.9.254
    prefer: true
os10_prefix_list:
- entries:
  - condition_list:
    - condition: ge
      prelen: 32
    mask: '0'
    net_num: 0.0.0.0
    number: 10
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: 31
    mask: '0'
    net_num: 0.0.0.0
    number: 20
    permit: true
    state: present
  name: deny_v4_host_routes
  state: present
  type: ipv4
- entries:
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 10.0.0.0
    number: 30
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 1.0.0.0
    number: 40
    permit: true
    state: present
  - condition_list:
    - condition: ge
      prelen: '24'
    mask: '16'
    net_num: 192.168.0.0
    number: 50
    permit: true
    state: present
  name: spine-leaf
  state: present
  type: ipv4
os10_route_map:
  route_map:
  - match:
    - ip_type: ipv4
      prefix_list: spine-leaf
    name: spine-leaf
    permit: true
    seq_num: 10
  - match:
    - ip_type: ipv4
      prefix_list: deny_v4_host_routes
    name: deny_v4_host_routes
    permit: true
    seq_num: 10
os10_system:
  hostname: fabric-LEAF-2
os10_vlan:
  Vlan 12:
    tagged_members:
    - port: port-channel 101
      state: present
    description: vlan12_local
    ip_and_mask: 172.16.12.2/24
    state: present    
  Vlan 101:
    description: vlan101_all_leafs
    ip_and_mask: null
    state: present
    tagged_members:
    - port: port-channel 101
      state: present
  Vlan 200:
    description: external vlan
    ip_and_mask: 10.10.0.2/16
    state: present
    tagged_members:
    - port: ethernet 1/1/4
      state: present
    - port: ethernet 1/1/5
      state: present
  Vlan 201:
    ip_and_mask: null
    state: present
  Vlan 301:
    ip_and_mask: null
    state: present
  Vlan 4000:
    description: iBGP_link
    ip_and_mask: 192.168.3.1/31
    state: present
os10_vlt:
  discovery_intf: 1/1/9
  discovery_intf_state: present
  domain: 127
  peer_routing: true
  vlt_mac: 00:00:00:00:00:12
  vlt_peers:
    Po 101:
      peer_lag: 101
  state: present

os10_lag:
  Po 101:
    type: dynamic
    min_links: 1
    lacp:
      long_timeout: true
      fast_switchover: true
    channel_members:
    - port: ethernet 1/1/1
      state: present
      mode: active
    state: present

os10_xstp:
  enable: true
  intf:
    port-channel 101:
      edge_port: true
      bpdu_guard: false
  rstp:
    bridge_priority: 4096
  type: rstp

os10_vrrp:
  Vlan 12:
    vrrp_group:
    - group_id: 12
      type: ipv4
      state: present
      virtual_address:
              - ip: 172.16.12.254
                state: present
      enable: true
      priority: 100
      preempt: true

os10_vrf:
  vrfdetails:
    - vrf_name: tenant1
      state: present
